### ISSUE TITLE
rollup is broken

### ISSUE THREAD

**Issue by Pomax** [Pomax/lib-font#108]
it renames `fetch` to `fetch$1`, which breaks everything, and there is no way to make it not do that from the looks of it, so either rollup gets taken out (I'd be all for that) or the fetch code is made a LOT more complex just to deal with rollup's insistence that a not-protected name `fetch` is a protected name.

**Comment by RoelN** [comment]
Does this mean `lib-font.js` currently doesn't have any of the new code, as it can't be rolled up? Any way to use the latest code with the latest master/npm package?

**Comment by Pomax** [comment]
lib-font.js does, there just isn't a `dist` dir anymore for the moment for prebundled legacy use

**Comment by RoelN** [comment]
Is this still relevant? 🤔

**Comment by Pomax** [comment]
not as far as I'm concerned.
