### ISSUE TITLE
How to use lookup type 7 (Extension Substitution)

### ISSUE THREAD

**Issue by RoelN** [Pomax/lib-font#112]
I get the offset to the extension table, but how to get the coverage?

```
extensionLookupType: 6
extensionOffset: 1868
substFormat: 1
```

**Comment by Pomax** [comment]
Ah, it looks like the substitution resolution is still missing. Let's get that added in.

**Comment by Pomax** [comment]
I've filed https://github.com/Pomax/lib-font/issues/113 to track this work.

**Comment by RoelN** [comment]
Thanks, @Pomax! 🙏
