### ISSUE TITLE
Error reading SVG table (ReferenceError: uint16 is not defined)

### ISSUE THREAD

**Issue by darknoon** [Pomax/lib-font#127]
### Context
Compiling a figma plugin (ui code) with esbuild
Trying to read the "SVG" table in an opentype font ([Abelone](https://www.fontself.com/colorfontweek/2018#abelone))

### Failing code

eg:
```typescript
import { Font } from "lib-font";

…
const myFont = new Font("namehere");
await myFont.fromDataBuffer(ab, f.name);
myFont.opentype.tables["SVG"] ← crashes here
…
```

It looks like [this line](https://github.com/Pomax/lib-font/blob/800233859b1fb6d023e50ff3b7434ef053024c1a/src/opentype/tables/simple/SVG.js#L13) is meant to say `p.uint16` perhaps?

As an aside, when I tried to add a failing test to `testing/browser/tests/test.otf.js`, throwing an exception seems to just hang the test host until timeout instead of failing the test.

**Comment by Pomax** [comment]
v2.3.6 published

**Comment by Pomax** [comment]
https://github.com/Pomax/lib-font/issues/128 filed to follow up on the testing issue.

**Comment by darknoon** [comment]
Thanks for the speedy turnaround!
