### ISSUE TITLE
Modify font object

### ISSUE THREAD

**Issue by moontypespace** [Pomax/lib-font#134]
Hi there,

I am wondering if lib-font is able to modify fonts as well or if reads the data only? If it reads only, are there any plans to add functionality to modify and save fonts? And if there are no such plans, do you know any other JavaScript library which is able to do so?

Thanks a lot in advance,
Olli

**Comment by moontypespace** [comment]
The basic question is, I am wondering if there is a javascript module similar to fonttools https://github.com/fonttools/fonttools ?

**Comment by Pomax** [comment]
There is no intention for this library to ever be able to modify/save fonts. But maybe https://github.com/opentypejs/opentype.js#writing-a-font does what you need?
