### ISSUE TITLE
Use the lib-font browser bundle in a webpack project.

### ISSUE THREAD

**Issue by matiasbenedetto** [Pomax/lib-font#135]
Hi :wave: I'm trying to use the browser bundle in a large project where the dependencies are managed using NPM and the project is built using webpack. I have a few questions about that:

It seems like I can not import `lib-font.browser.js`using the npm installed package. Can I?

If I `import { Font } from "lib-font"` I get errors about `fs` and `zlib` missing dependencies. I could avoid that failure by adding the following config to the webapck config file. But due to characteristics of this project I can't modify the webpack config file.

```
	resolve: {
		fallback: {
			zlib: false,
			fs: false,
		},
	},
```

Apart I tried copying the entire `lib-font.browser.js` file into my project's source code I get errors when building the app with webapck:

```
ERROR in lib-font.browser.js 14:2-14
  Module not found: Error: Can't resolve 'fs' in 'fonts-modal'
 ```
 
If I delete the references to fs and zlib from `lib-font.browser.js` it works as expected but I would like to avoid forking the package. So I return to my original question: Is there any way to include the lib-font browser bundle in a npm + webpack project without errors about missing dependencies?

Thanks for the great work!

**Comment by Pomax** [comment]
I'm a little confused why you would add the browser library to your bundle when it's already a standard JS library that you can load with a `<script>` tag your html (template)? You can access any out-of-bundle global via the universal `globalThis` keyword (which in the browser maps to `window` and in Node maps to `global`).

**Comment by youknowriad** [comment]
I think the idea here is to avoid polluting the global `window` with the API for this library. Any variable added like that globally becomes defecto an API for third-party developers of our app that we may not want to expose (for backwards compatibility reasons)

**Comment by Pomax** [comment]
https://github.com/Pomax/lib-font/#how-do-i-use-this-with-webpack
