### ISSUE TITLE
Supports CommonJS

### ISSUE THREAD

**Issue by yisibl** [Pomax/lib-font#137]
A lot of historical Node.js projects won't be able to migrate to ESM anytime soon, and I think it would be better to support CommonJS.

**Comment by Pomax** [comment]
All of them are perfectly capable of converting ESM to CJS themselves using quite a few tool options.

**Comment by yisibl** [comment]
Thanks, I've forked and released a separate package containing CJS: https://github.com/yisibl/lib-font/pull/1

**Comment by Pomax** [comment]
the license certain allows for that, but it's kind of a nonsense thing to do given the JS tools available to everyone in late 2023 to fix this problem if your codebase has a CJS/ESM problem.
